### ISSUE TITLE
部署在在Glitch 平台且设置了Argo 固定域名隧道的两个参数，输出节点里还是动态的

### ISSUE THREAD

**Issue by yidasanqian** [fscarmen2/Argo-Xray-JS-PaaS#2]
伪装域名并没有设置成功

**Comment by fscarmen** [comment]
你在哪个位置设置的，如何设置的？

**Comment by yidasanqian** [comment]
> 你在哪个位置设置的，如何设置的？

根据readme文档设置的，argo设置了，但是没起作用
![image](https://user-images.githubusercontent.com/10655188/227541739-2d6add27-9f74-4155-aad4-5f28aaaf28c0.png)

**Comment by fscarmen** [comment]
a

> > 你在哪个位置设置的，如何设置的？
> 
> 根据readme文档设置的，argo设置了，但是没起作用 ![image](https://user-images.githubusercontent.com/10655188/227541739-2d6add27-9f74-4155-aad4-5f28aaaf28c0.png)

<img width="1672" alt="image" src="https://user-images.githubusercontent.com/62703343/227604852-6cee32be-4732-4cb7-953d-7b44ec5cc3e1.png">

<img width="1636" alt="image" src="https://user-images.githubusercontent.com/62703343/227605325-04520d7d-93f4-4c64-9bdf-1db16de96e44.png">

**Comment by yidasanqian** [comment]
我看glitch部署日志中有报错，配置是按你上面的截图来的
![image](https://user-images.githubusercontent.com/10655188/227699910-7b50f426-d03a-4a7e-aa82-bcb76f6e256d.png)

**Comment by fscarmen** [comment]
你这个cloudflared是自己上传上去的吗？你删掉他，重新运行下，应该是没有赋执行权

**Comment by yidasanqian** [comment]
我重新新建项目部署，日志没报错了，但是tunnel还是未激活
![image](https://user-images.githubusercontent.com/10655188/227701054-073572b3-e193-4e43-973d-0f162f9aa44b.png)
![image](https://user-images.githubusercontent.com/10655188/227701120-bac236f6-b2fc-442a-9746-cf4d7231afb4.png)

**Comment by yidasanqian** [comment]
argo变量位置的问题

**Comment by fscarmen** [comment]
看你的截图，使用的是临时隧道的，还是没有解决吗？

**Comment by yidasanqian** [comment]
> 看你的截图，使用的是临时隧道的，还是没有解决吗？

解决了，谢谢你的回答
