### ISSUE TITLE
No Argo JS version?

### ISSUE THREAD

**Issue by mewchore** [fscarmen2/Argo-Xray-JS-PaaS#4]
Is it possible to release a version without the argo tunneling turned on as the default? I guess some websites do not appreciate using Argo tunneling. I deleted the argo lines from the bash script and the index file, but I couldn't get it running.

**Comment by fscarmen2** [comment]
You can try using another author's project at https://github.com/Misaka-blog/xray-for-nodejs

**Comment by mrezabidhendi** [comment]
Thanks for always responding in the quickest time.👌
