### ISSUE TITLE
codesandbox部署内存疯涨

### ISSUE THREAD

**Issue by dorccl4k** [fscarmen2/Argo-Xray-JS-PaaS#5]
<img width="351" alt="image" src="https://user-images.githubusercontent.com/101784938/229260144-8416c52b-630e-4b61-bcac-30ed19a88d6c.png">

**Comment by dorccl4k** [comment]
<img width="174" alt="image" src="https://user-images.githubusercontent.com/101784938/229260215-f06411a6-67d0-4563-a0e9-d7514c4e87a8.png">

**Comment by Neomanbeta** [comment]
把server.js里面的argo保活部分删掉就解决了。

**Comment by dorccl4k** [comment]
> 把server.js里面的argo保活部分删掉就解决了。

感谢，测试成功。
