### ISSUE TITLE
render似乎无法运行

### ISSUE THREAD

**Issue by Fangliding** [fscarmen2/Argo-Xray-JS-PaaS#7]
event里似乎一直处在deploy的状态 不结束 然后过段时间deploy失败
顺便一提 想在render部署得挪走仓库之后删掉readme不然秒封

**Comment by fscarmen** [comment]
https://github.com/fscarmen2/Render

这个项目，不用删 `README.md`

**Comment by fscarmen2** [comment]
有专门针对  Render 的细分项目： https://github.com/fscarmen2/Render

这个项目，不用删 `README.md`，不要直接引用我的库地址，你弄到你库下就行了

<img width="992" alt="image" src="https://user-images.githubusercontent.com/92626977/234605568-6e164644-13aa-429b-8d28-07c51fade01d.png">

**Comment by Fangliding** [comment]
> 有专门针对 Render 的细分项目： https://github.com/fscarmen2/Render
> 
> 这个项目，不用删 `README.md`，不要直接引用我的库地址，你弄到你库下就行了
> 
> <img alt="image" width="992" src="https://user-images.githubusercontent.com/92626977/234605568-6e164644-13aa-429b-8d28-07c51fade01d.png">

好 大佬回复神速
